// Copyright (C) 2001, Compaq Computer Corporation
// 
// This file is part of Vesta.
// 
// Vesta is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// Vesta is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with Vesta; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// Created on Wed Jul 23 08:29:10 PDT 1997 by heydon
// Last modified on Fri Apr 29 12:06:37 EDT 2005 by ken@xorian.net        
//      modified on Thu Aug  8 13:46:39 EDT 2002 by kcschalk@shr.intel.com
//      modified on Wed Jul 23 08:30:42 PDT 1997 by heydon

#ifndef _PK_PREFIX_SEQ
#define _PK_PREFIX_SEQ

#include <Basics.H>
#include <Sequence.H>
#include <PKPrefix.H>

typedef Sequence<PKPrefix::T,true> PKPrefixSeq;

#endif // _PK_PREFIX_SEQ
