// Copyright (C) 2001, Compaq Computer Corporation
// 
// This file is part of Vesta.
// 
// Vesta is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.
// 
// Vesta is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public
// License along with Vesta; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

// Last modified on Fri Jul 16 17:23:03 EDT 2004 by ken@xorian.net
//      modified on Mon Dec 23 14:18:03 PST 1996 by heydon

// This program generates a C file that declares the constant values for the
// implementation of the fingerprint module "FP.C".

#include <Basics.H>
#include "ByteModTable.H"

using std::cout;
using std::endl;

int main()
{
    cout << "// The table for computing raw fingerprints\n//\n";
    cout << "// This table was generated by the program \"TestFPTable\"\n//\n";
    cout << "// These used to be compiled in as constants, but are" << endl
	 << "// now generated when the fingerprinting library is" << endl
	 << "// initialized.  The output of this program can still" << endl
	 << "// serve as a test that the table generation algorithm" << endl
	 << "// is working correctly.\n\n";
    cout << "Poly ";

    // Write out "ByteModTable"
    cout << "ByteModTable[8][256] = {\n";
    for (int i = 0; i < 8; i++) {
	cout << "  { ";
	for (int j = 0; j < 256; j++) {
	    if (j > 0) cout << "    ";
	    cout << "{ ";
	    for (int ix = 0; ix < PolyVal::WordCnt; ix ++) {
		if (ix > 0) cout << "      ";
		char buff[17];
		sprintf(buff, "%016" FORMAT_LENGTH_INT_64 "x",
			ByteModTable[i][j].w[ix]);
		cout << "CONST_INT_64(0x" << buff << ")";
		if (ix < PolyVal::WordCnt-1) cout << "," << endl;
	    }
	    cout << " }";
	    if (j < 255) cout << ",";
	    cout << "\n";
	}
	cout << "  }";
	if (i < 7) cout << ",";
	cout << "\n";
    }      
    cout << "};\n";
    cout.flush();
    return(0);
}
